# Don't Remove Credit @vlcbox
# Subscribe Telegram Channel For Amazing Bot @vlcbox
# Ask Doubt on telegram @rickakhtar

"""
Experimental Telegram Rich Message Plugin for VLCBox.

Provides:
- /richtestping: Diagnostic ping command to verify plugin loading.
- /testrich: Minimal Rich Message API proof of concept with a buttons block.
- /richmovie: Static Rich Movie UI Prototype using structured blocks with native
  RichMessageButton rows INSIDE rich_message.blocks (no reply_markup keyboard).
- Isolated callback handlers for all prototype buttons.

Bot API 10.3: Uses InputRichBlockButtons with RichMessageButton objects.
Buttons are part of the rich message content, NOT a traditional inline keyboard.
"""

import html
import logging
from pyrogram import filters, enums, Client
from pyrogram.types import Message, CallbackQuery
from VLCBox.util.base_clients import MainBot
from VLCBox.util.rich import send_rich_message_api
from info import RICH_MOVIE_RESULTS

logger = logging.getLogger(__name__)
print(">>> VLCBox: plugins.rich successfully loaded <<<")


# ─────────────────────────────────────────────────────────────────────────────
# DIAGNOSTIC
# ─────────────────────────────────────────────────────────────────────────────

@MainBot.on_message(filters.command(["richtestping", "richping"]) & filters.incoming, group=1)
async def rich_test_ping_command(client, message: Message):
    """
    Diagnostic handler to verify whether the Rich plugin is properly loaded.
    Does NOT call Telegram's Rich Message API.
    """
    logger.info(f"RICH_DIAGNOSTIC: /richtestping received in chat_id={message.chat.id}")
    await message.reply_text("RICH PLUGIN LOADED ✅")


# ─────────────────────────────────────────────────────────────────────────────
# /testrich — Minimal PoC with a native Rich button block
# ─────────────────────────────────────────────────────────────────────────────

@MainBot.on_message(filters.command("testrich") & filters.incoming, group=1)
async def test_rich_command(client, message: Message):
    """
    Isolated test command for Telegram Rich Messages.
    Demonstrates a heading, paragraph, divider, and a buttons block (not reply_markup).
    """
    chat_id = message.chat.id
    logger.info(f"RICH_TEST: /testrich received in chat_id={chat_id}")

    blocks = [
        {
            "type": "heading",
            "text": {"type": "plain", "text": "🎬 VLCBox Rich Message Test"},
            "size": 1
        },
        {
            "type": "paragraph",
            "text": {"type": "plain", "text": "This is a genuine Telegram Rich Message generated by VLCBox. Buttons below are INSIDE the rich message."}
        },
        {
            "type": "divider"
        },
        {
            "type": "buttons",
            "buttons": [
                {
                    "text": "✅ TEST BUTTON",
                    "style": "primary",
                    "callback_data": "rich_test_btn_clicked"
                }
            ]
        }
    ]

    try:
        res = await send_rich_message_api(
            client=client,
            chat_id=chat_id,
            blocks=blocks,
            reply_to_message_id=message.id
        )

        if not res.get("success"):
            error_desc = res.get("description", res.get("error", "Unknown API error"))
            status_code = res.get("status_code", "Unknown")
            logger.warning(f"RICH_TEST: sendRichMessage failure: {status_code} - {error_desc}")
            await message.reply_text(
                f"⚠️ <b>Telegram Rich Message API Test Result</b>\n\n"
                f"<b>Status:</b> <code>Rejected / Failed</code>\n"
                f"<b>HTTP Code:</b> <code>{status_code}</code>\n"
                f"<b>Telegram API Response:</b> <code>{error_desc}</code>\n\n"
                f"<i>Note: Rich Messages are currently in experimental testing (RICH_MOVIE_RESULTS={RICH_MOVIE_RESULTS}).</i>",
                parse_mode=enums.ParseMode.HTML
            )
        else:
            logger.info(f"RICH_TEST: sendRichMessage succeeded for chat_id={chat_id}")
    except Exception as e:
        logger.error(f"RICH_TEST: Exception executing /testrich: {e}", exc_info=True)
        await message.reply_text(
            f"❌ <b>Rich Handler Exception:</b> <code>{html.escape(str(e))}</code>",
            parse_mode=enums.ParseMode.HTML
        )


# ─────────────────────────────────────────────────────────────────────────────
# /richmovie — Full Rich Movie UI with native button blocks
# ─────────────────────────────────────────────────────────────────────────────

@MainBot.on_message(filters.command("richmovie") & filters.incoming, group=1)
async def rich_movie_prototype_command(client, message: Message):
    """
    Static Rich Movie UI Prototype.

    Structure:
    1. Movie heading (size=1)
    2. Metadata paragraph
    3. Divider
    4. Storyline — collapsible details block (InputRichBlockDetails)
    5. Divider
    6. Button Row 1: QUALITY + LANGUAGE  (InputRichBlockButtons)
    7. Divider
    8. Available Files heading (size=2)
    9. Files table (InputRichBlockTable, compact)
    10. Divider
    11. Button Row 2: WATCH + DOWNLOAD  (InputRichBlockButtons)
    12. Button Row 3: SEND ALL FILES    (InputRichBlockButtons)
    13. Divider
    14. Footer

    Buttons are INSIDE rich_message.blocks — NOT in reply_markup.
    No traditional inline keyboard is attached.
    """
    chat_id = message.chat.id
    logger.info(f"RICH_MOVIE: /richmovie received in chat_id={chat_id}")

    blocks = [
        # ── 1. Movie Title ──────────────────────────────────────────────────
        {
            "type": "heading",
            "text": {"type": "plain", "text": "🎬 SPIDER-MAN: NO WAY HOME"},
            "size": 1
        },

        # ── 2. Metadata ─────────────────────────────────────────────────────
        {
            "type": "paragraph",
            "text": {"type": "plain", "text": "2021  •  Action  •  Adventure  •  Sci-Fi\n⭐ 8.2 / 10  •  2h 28m"}
        },

        # ── 3. Divider ──────────────────────────────────────────────────────
        {"type": "divider"},

        # ── 4. Storyline — collapsible details block ─────────────────────────
        {
            "type": "details",
            "summary": {"type": "plain", "text": "📖 STORYLINE  ▾ READ MORE"},
            "is_open": False,
            "blocks": [
                {
                    "type": "paragraph",
                    "text": {
                        "type": "plain",
                        "text": (
                            "With Spider-Man's identity now revealed, our friendly neighborhood "
                            "web-slinger is unmasked and no longer able to separate his normal life "
                            "from the high-stakes of being a Super Hero. When he asks for help from "
                            "Doctor Strange, the stakes become even more dangerous, forcing him to "
                            "discover what it truly means to be Spider-Man."
                        )
                    }
                }
            ]
        },

        # ── 5. Divider ──────────────────────────────────────────────────────
        {"type": "divider"},

        # ── 6. Button Row 1: QUALITY + LANGUAGE ─────────────────────────────
        # These are native Rich Message buttons — NOT reply_markup
        {
            "type": "buttons",
            "buttons": [
                {
                    "text": "🎞 QUALITY",
                    "style": "primary",
                    "callback_data": "rich_movie_quality"
                },
                {
                    "text": "🌐 LANGUAGE",
                    "style": "primary",
                    "callback_data": "rich_movie_language"
                }
            ]
        },

        # ── 7. Divider ──────────────────────────────────────────────────────
        {"type": "divider"},

        # ── 8. Available Files heading ───────────────────────────────────────
        {
            "type": "heading",
            "text": {"type": "plain", "text": "📁 AVAILABLE FILES"},
            "size": 2
        },

        # ── 9. Files table (compact, bordered) ──────────────────────────────
        # InputRichBlockTable with cells (2D array of RichBlockTableCell)
        {
            "type": "table",
            "is_compact": True,
            "is_bordered": True,
            "is_striped": True,
            "cells": [
                [
                    {"text": {"type": "plain", "text": "Quality"}, "is_header": True},
                    {"text": {"type": "plain", "text": "Language"}, "is_header": True},
                    {"text": {"type": "plain", "text": "Size"}, "is_header": True}
                ],
                [
                    {"text": {"type": "plain", "text": "1080p"}},
                    {"text": {"type": "plain", "text": "Hindi"}},
                    {"text": {"type": "plain", "text": "3.2 GB"}}
                ],
                [
                    {"text": {"type": "plain", "text": "1080p"}},
                    {"text": {"type": "plain", "text": "English"}},
                    {"text": {"type": "plain", "text": "3.5 GB"}}
                ],
                [
                    {"text": {"type": "plain", "text": "720p"}},
                    {"text": {"type": "plain", "text": "Hindi"}},
                    {"text": {"type": "plain", "text": "1.8 GB"}}
                ],
                [
                    {"text": {"type": "plain", "text": "720p"}},
                    {"text": {"type": "plain", "text": "English"}},
                    {"text": {"type": "plain", "text": "2.0 GB"}}
                ]
            ]
        },

        # ── 10. Divider ─────────────────────────────────────────────────────
        {"type": "divider"},

        # ── 11. Button Row 2: WATCH + DOWNLOAD ──────────────────────────────
        {
            "type": "buttons",
            "buttons": [
                {
                    "text": "▶ WATCH",
                    "style": "success",
                    "callback_data": "rich_movie_watch"
                },
                {
                    "text": "⬇ DOWNLOAD",
                    "style": "primary",
                    "callback_data": "rich_movie_download"
                }
            ]
        },

        # ── 12. Button Row 3: SEND ALL FILES ────────────────────────────────
        {
            "type": "buttons",
            "buttons": [
                {
                    "text": "📂 SEND ALL FILES",
                    "style": "primary",
                    "callback_data": "rich_movie_send_all"
                }
            ]
        },

        # ── 13. Divider ─────────────────────────────────────────────────────
        {"type": "divider"},

        # ── 14. Footer ──────────────────────────────────────────────────────
        {
            "type": "footer",
            "text": {"type": "plain", "text": "Requested by RICK  •  Powered by VLCBox"}
        }
    ]

    try:
        # NO reply_markup — buttons are inside blocks
        res = await send_rich_message_api(
            client=client,
            chat_id=chat_id,
            blocks=blocks,
            reply_to_message_id=message.id
        )

        if not res.get("success"):
            error_desc = res.get("description", res.get("error", "Unknown API error"))
            status_code = res.get("status_code", "Unknown")
            logger.warning(f"RICH_MOVIE: sendRichMessage failure: {status_code} - {error_desc}")
            await message.reply_text(
                f"⚠️ <b>Rich Movie Prototype Result</b>\n\n"
                f"<b>Status:</b> <code>Rejected / Failed</code>\n"
                f"<b>HTTP Code:</b> <code>{status_code}</code>\n"
                f"<b>Telegram API Response:</b> <code>{error_desc}</code>\n\n"
                f"<i>Note: Rich Messages are experimental (RICH_MOVIE_RESULTS={RICH_MOVIE_RESULTS}).</i>",
                parse_mode=enums.ParseMode.HTML
            )
        else:
            logger.info(f"RICH_MOVIE: sendRichMessage succeeded for chat_id={chat_id}")
    except Exception as e:
        logger.error(f"RICH_MOVIE: Exception executing /richmovie: {e}", exc_info=True)
        await message.reply_text(
            f"❌ <b>Rich Movie Handler Exception:</b> <code>{html.escape(str(e))}</code>",
            parse_mode=enums.ParseMode.HTML
        )


# ─────────────────────────────────────────────────────────────────────────────
# CALLBACK HANDLERS — for all Rich Message buttons
# ─────────────────────────────────────────────────────────────────────────────

@MainBot.on_callback_query(filters.regex(r"^rich_test_btn_clicked$"), group=1)
async def rich_test_callback_handler(client: Client, query: CallbackQuery):
    """Callback for the /testrich test button."""
    logger.info(f"RICH_CALLBACK: rich_test_btn_clicked from user={query.from_user.id}")
    await query.answer("✅ Rich Message button works!", show_alert=True)


@MainBot.on_callback_query(filters.regex(r"^rich_movie_quality$"), group=1)
async def rich_movie_quality_callback_handler(client: Client, query: CallbackQuery):
    """Callback for the QUALITY button in the Rich Movie UI."""
    logger.info(f"RICH_CALLBACK: rich_movie_quality from user={query.from_user.id}")
    await query.answer("🎞 Quality button works! (prototype)", show_alert=True)


@MainBot.on_callback_query(filters.regex(r"^rich_movie_language$"), group=1)
async def rich_movie_language_callback_handler(client: Client, query: CallbackQuery):
    """Callback for the LANGUAGE button in the Rich Movie UI."""
    logger.info(f"RICH_CALLBACK: rich_movie_language from user={query.from_user.id}")
    await query.answer("🌐 Language button works! (prototype)", show_alert=True)


@MainBot.on_callback_query(filters.regex(r"^rich_movie_watch$"), group=1)
async def rich_movie_watch_callback_handler(client: Client, query: CallbackQuery):
    """Callback for the WATCH button in the Rich Movie UI."""
    logger.info(f"RICH_CALLBACK: rich_movie_watch from user={query.from_user.id}")
    await query.answer("▶ Watch button works! (prototype)", show_alert=True)


@MainBot.on_callback_query(filters.regex(r"^rich_movie_download$"), group=1)
async def rich_movie_download_callback_handler(client: Client, query: CallbackQuery):
    """Callback for the DOWNLOAD button in the Rich Movie UI."""
    logger.info(f"RICH_CALLBACK: rich_movie_download from user={query.from_user.id}")
    await query.answer("⬇ Download button works! (prototype)", show_alert=True)


@MainBot.on_callback_query(filters.regex(r"^rich_movie_send_all$"), group=1)
async def rich_movie_send_all_callback_handler(client: Client, query: CallbackQuery):
    """Callback for the SEND ALL FILES button in the Rich Movie UI."""
    logger.info(f"RICH_CALLBACK: rich_movie_send_all from user={query.from_user.id}")
    await query.answer("📂 Send All Files button works! (prototype)", show_alert=True)
