# Don't Remove Credit @vlcbox
# Subscribe Telegram Channel For Amazing Bot @vlcbox
# Ask Doubt on telegram @rickakhtar

"""
Experimental Telegram Rich Message Proof of Concept & Static Prototype Plugin for VLCBox.

Provides:
- /richtestping: Diagnostic ping command to verify plugin loading.
- /testrich: Minimal Rich Message API proof of concept.
- /richmovie: Static Rich Movie UI Prototype using structured blocks (heading, table, dividers, action buttons).
- Isolated callback handlers for prototype demonstration buttons.
"""

import html
import logging
from pyrogram import filters, enums, Client
from pyrogram.types import Message, CallbackQuery
from VLCBox.util.base_clients import MainBot
from VLCBox.util.rich import send_rich_message_api
from info import RICH_MOVIE_RESULTS

logger = logging.getLogger(__name__)
print(">>> VLCBox: plugins.rich successfully loaded <<<")


@MainBot.on_message(filters.command(["richtestping", "richping"]) & filters.incoming, group=1)
async def rich_test_ping_command(client, message: Message):
    """
    Diagnostic handler to verify whether the Rich plugin is properly loaded and registered.
    Does NOT call Telegram's Rich Message API.
    """
    logger.info(f"RICH_DIAGNOSTIC: /richtestping received in chat_id={message.chat.id}")
    await message.reply_text("RICH PLUGIN LOADED ✅")


@MainBot.on_message(filters.command("testrich") & filters.incoming, group=1)
async def test_rich_command(client, message: Message):
    """
    Isolated test command for Telegram Rich Messages.
    Works in both private chat and groups/supergroups.
    """
    chat_id = message.chat.id
    logger.info(f"RICH_TEST: /testrich received in chat_id={chat_id}")
    
    # Construct minimal rich blocks according to specification
    blocks = [
        {
            "type": "heading",
            "text": "🎬 VLCBox Rich Message Test",
            "size": 1
        },
        {
            "type": "paragraph",
            "text": "This is a genuine Telegram Rich Message generated by VLCBox."
        },
        {
            "type": "divider"
        },
        {
            "type": "list",
            "items": [
                {"text": "Rich formatting"},
                {"text": "Structured blocks"},
                {"text": "Telegram-native rendering"}
            ]
        },
        {
            "type": "table",
            "headers": ["Quality", "Size"],
            "rows": [
                ["1080p", "3.2 GB"],
                ["720p", "1.8 GB"]
            ]
        }
    ]

    reply_markup = {
        "inline_keyboard": [
            [{"text": "TEST BUTTON", "callback_data": "rich_test_btn_clicked"}]
        ]
    }

    try:
        # Call genuine Telegram Rich Message API directly
        res = await send_rich_message_api(
            client=client,
            chat_id=chat_id,
            blocks=blocks,
            reply_markup=reply_markup,
            reply_to_message_id=message.id
        )

        if not res.get("success"):
            error_desc = res.get("description", res.get("error", "Unknown API error"))
            status_code = res.get("status_code", "Unknown")
            logger.warning(f"RICH_TEST: sendRichMessage returned failure: {status_code} - {error_desc}")
            await message.reply_text(
                f"⚠️ <b>Telegram Rich Message API Test Result</b>\n\n"
                f"<b>Status:</b> <code>Rejected / Failed</code>\n"
                f"<b>HTTP Code:</b> <code>{status_code}</code>\n"
                f"<b>Telegram API Response:</b> <code>{error_desc}</code>\n\n"
                f"<i>Note: Rich Messages are currently in experimental testing (RICH_MOVIE_RESULTS={RICH_MOVIE_RESULTS}).</i>",
                parse_mode=enums.ParseMode.HTML
            )
        else:
            logger.info(f"RICH_TEST: sendRichMessage succeeded for chat_id={chat_id}")
    except Exception as e:
        logger.error(f"RICH_TEST: Exception executing /testrich: {e}", exc_info=True)
        await message.reply_text(
            f"❌ <b>Rich Handler Exception:</b> <code>{html.escape(str(e))}</code>",
            parse_mode=enums.ParseMode.HTML
        )


@MainBot.on_message(filters.command("richmovie") & filters.incoming, group=1)
async def rich_movie_prototype_command(client, message: Message):
    """
    Static Rich Movie UI Prototype command.
    Sends a structured Rich Message card with sample movie metadata, table, and buttons.
    Operates in private chat and groups/supergroups as a normal message.
    """
    chat_id = message.chat.id
    logger.info(f"RICH_MOVIE: /richmovie received in chat_id={chat_id}")

    # Construct static rich movie card blocks
    blocks = [
        {
            "type": "heading",
            "text": "🎬 SPIDER-MAN: NO WAY HOME",
            "size": 1
        },
        {
            "type": "paragraph",
            "text": "2021 • Action • Adventure • Sci-Fi\n⭐ 8.2/10"
        },
        {
            "type": "divider"
        },
        {
            "type": "heading",
            "text": "📖 STORYLINE",
            "size": 2
        },
        {
            "type": "paragraph",
            "text": "Peter Parker's identity is revealed, causing his life to become increasingly difficult. He seeks help to restore his secret identity and faces unexpected consequences."
        },
        {
            "type": "divider"
        },
        {
            "type": "heading",
            "text": "📁 AVAILABLE FILES",
            "size": 2
        },
        {
            "type": "table",
            "headers": ["Quality", "Language", "Size"],
            "rows": [
                ["1080p", "Hindi", "3.2 GB"],
                ["1080p", "English", "3.5 GB"],
                ["720p", "Hindi", "1.8 GB"],
                ["720p", "English", "2.0 GB"]
            ]
        }
    ]

    reply_markup = {
        "inline_keyboard": [
            [
                {"text": "🎞 QUALITY", "callback_data": "rich_movie_quality"},
                {"text": "🌐 LANGUAGE", "callback_data": "rich_movie_language"}
            ],
            [
                {"text": "▶ WATCH", "callback_data": "rich_movie_watch"},
                {"text": "⬇ DOWNLOAD", "callback_data": "rich_movie_download"}
            ]
        ]
    }

    try:
        # Call genuine Telegram Rich Message API directly
        res = await send_rich_message_api(
            client=client,
            chat_id=chat_id,
            blocks=blocks,
            reply_markup=reply_markup,
            reply_to_message_id=message.id
        )

        if not res.get("success"):
            error_desc = res.get("description", res.get("error", "Unknown API error"))
            status_code = res.get("status_code", "Unknown")
            logger.warning(f"RICH_MOVIE: sendRichMessage returned failure: {status_code} - {error_desc}")
            await message.reply_text(
                f"⚠️ <b>Static Rich Movie Prototype Result</b>\n\n"
                f"<b>Status:</b> <code>Rejected / Failed</code>\n"
                f"<b>HTTP Code:</b> <code>{status_code}</code>\n"
                f"<b>Telegram API Response:</b> <code>{error_desc}</code>\n\n"
                f"<i>Note: Rich Messages are currently in experimental testing (RICH_MOVIE_RESULTS={RICH_MOVIE_RESULTS}).</i>",
                parse_mode=enums.ParseMode.HTML
            )
        else:
            logger.info(f"RICH_MOVIE: sendRichMessage succeeded for chat_id={chat_id}")
    except Exception as e:
        logger.error(f"RICH_MOVIE: Exception executing /richmovie: {e}", exc_info=True)
        await message.reply_text(
            f"❌ <b>Rich Movie Handler Exception:</b> <code>{html.escape(str(e))}</code>",
            parse_mode=enums.ParseMode.HTML
        )


@MainBot.on_callback_query(filters.regex(r"^rich_test_btn_clicked$"))
async def rich_test_callback_handler(client: Client, query: CallbackQuery):
    """
    Isolated callback handler for the test Rich Message button.
    """
    await query.answer("✅ Rich Message button works.", show_alert=True)


@MainBot.on_callback_query(filters.regex(r"^rich_movie_quality$"))
async def rich_movie_quality_callback_handler(client: Client, query: CallbackQuery):
    """
    Isolated callback handler for the prototype Quality button.
    """
    await query.answer("Quality button works.", show_alert=True)


@MainBot.on_callback_query(filters.regex(r"^rich_movie_language$"))
async def rich_movie_language_callback_handler(client: Client, query: CallbackQuery):
    """
    Isolated callback handler for the prototype Language button.
    """
    await query.answer("Language button works.", show_alert=True)


@MainBot.on_callback_query(filters.regex(r"^rich_movie_watch$"))
async def rich_movie_watch_callback_handler(client: Client, query: CallbackQuery):
    """
    Isolated callback handler for the prototype Watch button.
    """
    await query.answer("Watch button works.", show_alert=True)


@MainBot.on_callback_query(filters.regex(r"^rich_movie_download$"))
async def rich_movie_download_callback_handler(client: Client, query: CallbackQuery):
    """
    Isolated callback handler for the prototype Download button.
    """
    await query.answer("Download button works.", show_alert=True)
